// Story: US-020
package com.northbank.registration.audit.domain.model;

public enum AuditActionType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    ACCOUNT_OPENED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_ACTIVATED,
    TRANSFER_SUBMITTED,
    TRANSFER_BLOCKED,
    TRANSFER_COMPLETED,
    FRAUD_RULE_CREATED,
    FRAUD_RULE_UPDATED,
    FRAUD_RULE_DELETED,
    TRANSACTION_UNBLOCKED,
    TRANSACTION_REJECTED,
    CUSTOMER_DEACTIVATED,
    CUSTOMER_UNLOCKED
}
